#!/bin/sh

export HC_HOME=../..
export JAR="${HC_HOME}"/target/scala-*/Horn-Concurrency-assembly-*.jar
export JAVA_OPTS="-Xmx2024m -Xss20000k -cp $JAR"

for mainClass in hornconcurrency.Main; do
    echo
    echo $mainClass
    java $JAVA_OPTS $mainClass 2>&1 | grep -v time | grep -v 'ms)' | sed -e 's/Map(.*$//g'
done

